config/routes.rb
Rails.application.routes.draw do
  get 'grocery_items_controller/index'

  root 'groups#index'
  devise_for :users, :controllers => {registrations: 'registrations' }

  resources :groups, only: [:index, :show, :create, :destroy, :edit, :update] do
    resources :memberships, only: [:create, :destroy]
    resources :grocery_lists, only: [:index, :show, :new, :create, :destroy] do
      resources :receipts, only: [:index, :create]
    end
  end
  resources :grocery_lists, only: [:index, :show, :new, :create, :destroy] do
    resources :supplies, only: [:index, :new, :create]
    resources :grocery_items, only: [:edit, :update]
  end

  resources :grocery_lists do
    resources :grocery_items
    resources :receipts
  end
end

app/models/grocery_item.rb
class GroceryItem < ActiveRecord::Base
  validates :name, presence: true
  validates :quantity, presence: true

  belongs_to :grocery_list
end

app/models/grocery_list.rb
class GroceryList < ActiveRecord::Base
  validates :name, presence: true

  has_many   :grocery_items
  has_many   :receipts
  has_many   :supplies
  belongs_to :group
  has_many :supplies
end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :memberships
  has_many :users, through: :memberships
  has_many :grocery_lists

  validates :name, presence: true
end

app/models/guest_user.rb
class GuestUser
  def in_group?(*)
    false
  end

  def authenticated?
    false
  end
end

app/models/membership.rb
class Membership < ActiveRecord::Base
  belongs_to :user
  belongs_to :group

  validates :user, presence: true
  validates :group, presence: true
end

app/models/receipt.rb
class Receipt < ActiveRecord::Base
  mount_uploader :photo, ReceiptPhotoUploader
  belongs_to :membership
  belongs_to :grocery_list

  validates :membership, presence: true
  validates :grocery_list, presence: true
  validates :photo, presence: true

  def uploaded_by
    membership.user.full_name
  end
end

app/models/supply.rb
class Supply < ActiveRecord::Base
  validates :item, presence: true

  belongs_to :grocery_list
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :memberships
  has_many :groups, through: :memberships

  def full_name
    first_name + " " + last_name
  end

  def in_group?(group)
    groups.include?(group)
  end

  def authenticated?
    true
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    if warden.authenticate
      super
    else
      GuestUser.new
    end
  end
end

app/controllers/grocery_items_controller.rb
class GroceryItemsController < ApplicationController
  def index
  end

  def edit
    @grocery_list = GroceryList.find(params[:grocery_list_id])
    @grocery_item = GroceryItem.find(params[:id])
  end

  def update
    @grocery_list = GroceryList.find(params[:grocery_list_id])
    @grocery_item = GroceryItem.find(params[:id])
    @group = @grocery_list.group

    if @grocery_item.update(grocery_item_params)
      flash[:notice] = "Item has been updated."
      redirect_to group_path(@group)
    else
      flash[:notice] = @grocery_item.errors.full_messages.join("! ")
      render :edit
    end
  end

  private

  def grocery_item_params
    params.require(:grocery_item).permit(:name, :expiration_date, :quantity)
  end
end

app/controllers/grocery_lists_controller.rb
class GroceryListsController < ApplicationController
  def index

  end
  
  def create
    @group = Group.find params["group_id"]
    GroceryList.create(:name => params["grocery_list"]["name"], :group_id => params["group_id"])
    redirect_to group_path(@group)
  end

  def destroy
    @group = Group.find params["group_id"]
    @grocery_list = @group.grocery_lists.find(params[:id])
    @grocery_list.destroy
    redirect_to group_path(@group)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def index
    @groups = Group.all
    @group  = Group.new
  end

  def show
    @group         = Group.find(params[:id])
    @membership    = Membership.find_by(user: current_user, group: @group)
    @grocery_lists = GroceryList.where(group_id: @group.id)
    @grocery_list  = GroceryList.new
    @grocery_items = GroceryItem.where(grocery_list_id: @grocery_lists)
    @supply        = Supply.new
    @supplies      = Supply.where(grocery_list_id: @grocery_lists)
  end

  def edit
    @group = Group.find(params[:id])
  end

  def update
    @group = Group.find(params[:id])
    if @group.update(group_params)
      redirect_to @group
    else
      flash[:notice] = @group.errors.full_messages.join("! ")
      render :edit
    end
  end

  def create
    @group  = Group.new(group_params)
    if @group.save
      Membership.create(group: @group, user: current_user)
      flash[:notice] = "Group added."
      redirect_to root_path
    else
      @groups = Group.all
      render :index
    end
  end

  def edit
    @group = Group.find(params[:id])
  end

  def update
    @group = Group.find(params[:id])
    if @group.update(group_params)
      redirect_to @group
    else
      flash[:notice] = @group.errors.full_messages.join("! ")
      render :edit
    end
  end

  def destroy
    @group = Group.find(params[:id])
    @group.destroy
    redirect_to root_path
  end

  private

  def group_params
    params.require(:group).permit(:name)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/controllers/memberships_controller.rb
class MembershipsController < ApplicationController
  before_action :authenticate_user!

  def create
    @group = Group.find(params[:group_id])
    @membership = Membership.new(user: current_user, group: @group)
    if @membership.save
      flash[:notice] = "You have joined the group!"
    end

    redirect_to @group
  end

  def destroy
    @group = Group.find(params[:group_id])
    @membership = Membership.find_by(user: current_user, group: @group)

    if @membership.destroy
      flash[:notice] = "You have left the group."
      redirect_to @group
    end
  end
end

app/controllers/receipts_controller.rb
class ReceiptsController < ApplicationController
  def index
    @group = Group.find(params[:group_id])
    @grocery_list = GroceryList.find(params[:grocery_list_id])
    @receipt = Receipt.new
    @receipts = Receipt.where(grocery_list: params[:grocery_list_id])
  end

  def create
    @group = Group.find(params[:group_id])
    @grocery_list = GroceryList.find(params[:grocery_list_id])
    @membership = Membership.find_by(group: @group, user: current_user)
    @receipt = Receipt.new(receipt_params)
    @receipt.membership = @membership
    @receipt.grocery_list = @grocery_list

    if @receipt.save
      flash[:notice] = "Receipt Created!"
    end

    redirect_to group_grocery_list_receipts_path(@group, @grocery_list)
  end

  private

  def receipt_params
    params.require(:receipt).permit(:photo)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/supplies_controller.rb
class SuppliesController < ApplicationController
  def new 

  end

  def index
    binding.pry
  end

  def create
    @grocery_list = GroceryList.find params["grocery_list_id"]
    Supply.create(:item => params["supply"]["item"], :grocery_list_id => params["grocery_list_id"])
    redirect_to group_path(@grocery_list.group)
  end
end

app/helpers/grocery_items_controller_helper.rb
module GroceryItemsControllerHelper
end

app/views/grocery_items/edit.html.erb
<div class='row'>
  <h1>Edit this item</h1>
  <%= form_for [@grocery_list, @grocery_item],
    url: grocery_list_grocery_item_path(@grocery_list, @grocery_item) do |t| %>
    <%= t.label :name %>
    <%= t.text_field :name %>
    <%= t.label :quantity %>
    <%= t.text_field :quantity %>

    <%= t.submit "Update", class: "button radius" %>
  <% end %>
</div>

app/views/groups/_new.html.erb
<%= form_for @group, url: groups_path(@group) do |f| %>
  <% if @group.errors.any? %>
  <div id="error_explanation">
   <ul>
     <% @group.errors.full_messages.each do |message| %>
       <li><%= message %></li>
     <% end %>
   </ul>
  </div>
  <% end %>
  <%= f.text_field :name, placeholder: "Add new group" %>
  <%= f.submit "Add", class: "button postfix" %>
<% end %>

app/views/groups/_new_supply.html.erb
<p>Add to the supplies for this group:</p>
<%= form_for [grocery_list, @supply] do |f| %>
  <%= f.label :item %>
  <%= f.text_field :item %>
  <%= f.submit "Add Item" %>
<%-end-%>

app/views/groups/edit.html.erb
<div class='row'>
  <h1>Edit this group</h1>
  <%= form_for @group do |t| %>
    <%= t.label :name %>
    <%= t.text_field :name %>

    <%= t.submit "Submit", class: "button radius" %>
  <% end %>
</div>

app/views/groups/index.html.erb
<div class="row homepage">
  <h1>Groups</h1>

  <fieldset class="groupNameList">
    <% @groups.each do |group| %>
      <div><%= link_to "#{group.name}", group_path(group.id) %></div>
    <% end %>
  </fieldset>

    <div class="newGroup">
      <% if current_user.authenticated? %>
        <%= render "groups/new" %>
      <% end %>
    </div>
</div>

app/views/groups/show.html.erb
<div class="row">
  <h2><%=@group.name%></h2>

  <%= link_to "Edit", [:edit, @group], class: "button tiny radius" %>
  <%= link_to "Delete Group", group_path(@group), method: :delete, class: "button tiny radius" %>
  <% if user_signed_in? && current_user.groups.include?(@group) %>
    <%= link_to "Leave Group!", group_membership_path(@group, @membership), method: :delete, class: "button tiny radius" %>
  <% else %>
    <%= link_to "Join Group!", group_memberships_path(@group), method: :post, class: "button tiny radius" %>
  <%-end-%>
  <h4>These are the members of this group</h4>
  <%= "This group currently has no members" if @group.users.empty? %>
  <% @group.users.each do |user| %>
    <%= "#{user.first_name} #{user.last_name}" %>
  <%-end-%>
  <p><%= form_for [@group, @grocery_list] do |f| %>
    Add Your Group List Here

    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.submit "Create List" %>
  <%-end-%></p>

<<<<<<< HEAD
  <%= "This group currently has no lists" if @grocery_lists.empty? %>
  <ul>
  <% @grocery_lists.each do |grocery_list| %>
    <li><h3><%= grocery_list.name %> | <%= link_to "Delete List", group_grocery_list_path(@group, grocery_list), method: :delete %> </h3></li>
    <div class="row">
      <div class="small-6 column">
        <h4>Surpries Supplies!</h4>
        <p>Add to the supplies for this group:</p>
        <%= form_for [grocery_list, @supply] do |f| %>
          <%= f.label :item %>
          <%= f.text_field :item %>
          <%= f.submit "Add Item" %>
        <%-end-%>
        <ul><% @supplies.each do |supply| %>
          <li><%= supply.item %></li>
        <%-end-%></ul>
      </div>
      <div class="small-6 column">
      <h4>Receipt Items</h4>
      <p>This side is mostly a placeholder for the list of items we pull from receipts using HP's OCR reader</p>
      <p>But it would be really cool if this worked!</p>
      <p>Trust me!</p>
      <p>By pull data from receipts, we could streamline cost sharing</p>
      <p>We could also have a simple checklist for groceries when someone at home finishes the milk or the the Twinkies go bad</p>
      <p>"But Twinkies don't go bad!" you say?</p>
      <p>They do</p>
        <ul><% @grocery_items.each do |grocery_item| %>
          <li><%= grocery_item.name %></li>
          <li><%= grocery_item.quantity %> </li>
          <li><%= grocery_item.expiration_date %></li>
          <li><%= link_to "Edit Item", edit_grocery_list_grocery_item_path(grocery_list, grocery_item) %></li>
        <%-end-%></ul>
        <%= link_to "View Receipts", group_grocery_list_receipts_path(@group, grocery_list) %>
      </div>
    </div>
  <%-end-%>
  </ul>
</div>

app/views/homes/index.html.erb
<div class="cookie-monster">
  <img src="http://i.dailymail.co.uk/i/pix/2013/09/22/article-0-18297CEF00000578-775_634x426.jpg" class="cookiemonster"alt="Cookie Monster">
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shoppr</title>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= csrf_meta_tags %>
</head>
<body>

  <nav class="top-bar">
    <ul class="title-area">
      <li class="name">
        <h1><a href="/">Shoppr</a></h1>
      </li>
    </ul>

    <section class="top-bar-section">
      <ul class="right">
        <%- if current_user.authenticated? -%>
          <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
        <%- else -%>
          <li><%= link_to 'Sign Up', new_user_registration_path %></li>
          <li><%= link_to 'Sign In', new_user_session_path %></li>
        <%- end -%>
      </ul>
    </section>
  </nav>

  <%- flash.each do |key, value| -%>
    <div class="flash flash-<%= key %>">
      <%= value %>
    </div>
  <%- end -%>

  <%= yield %>

  <%= javascript_include_tag 'application' %>
  <%= yield :extra_footer %>
</body>
</html>

app/views/receipts/_form.html.erb
<%= form_for [@group, @grocery_list, @receipt] do |f| %>
  <%= f.file_field :photo, id: "receipt_field" %>
  <%= f.submit "Upload New Receipt", class: "button postfix" %>
<% end %>

<%= form_for [@group, @grocery_list, @receipt] do |f| %>
  <%= f.label :photo, 'Receipt URL' %>
  <%=f.text_field :photo %>
  <%= f.submit 'Add receipt' %>
<%-end-%>

app/views/receipts/index.html.erb
<ul>
  <% @receipts.each do |receipt| %>
    Receipt by <%= receipt.uploaded_by %>
    <%= image_tag(receipt.photo) %>
  <% end %>
</ul>

<%= render 'form' %>